version: '3'

services:
  db:
    container_name: mysql_worker
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "our_user"
      MYSQL_PASSWORD: "our_password"
    ports:
      - "4242:3306"
    expose:
      - "3306"
    volumes:
      - our_data:/var/lib/mysql

volumes:
  our_data: